modLoader = "javafml"
loaderVersion = "[43,)"
issueTrackerURL = "https://github.com/TimStewartJ/TheMightyArchitectury/issues"
license = "MIT"

[[mods]]
modId = "mightyarchitect"
version = "${version}"
displayName = "The Mighty Architect"
authors = "simibubi, timmie"
description = '''
1.19.2 Architectury port of The Mighty Architect. Design elaborate buildings within a minute!
'''
#logoFile = ""

[[dependencies.mightyarchitect]]
modId = "forge"
mandatory = true
versionRange = "[43,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.mightyarchitect]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19.2,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.mightyarchitect]]
modId = "architectury"
mandatory = true
versionRange = "[6.2.43,)"
ordering = "AFTER"
side = "BOTH"