modLoader = "javafml"
loaderVersion = "[46,)"
issueTrackerURL = "https://github.com/TimStewartJ/TheMightyArchitectury/issues"
license = "MIT"

[[mods]]
modId = "mightyarchitect"
version = "${version}"
displayName = "The Mighty Architect"
authors = "simibubi, timmie"
description = '''
Architectury port of The Mighty Architect. Design elaborate buildings within a minute!
'''
#logoFile = ""

[[dependencies.mightyarchitect]]
modId = "forge"
mandatory = true
versionRange = "[46,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.mightyarchitect]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.0,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.mightyarchitect]]
modId = "architectury"
mandatory = true
versionRange = "[9.0.8,)"
ordering = "AFTER"
side = "BOTH"